messages:
  set-checking-room: '&aLocations set successfully!'
  if-console: '&cYou must be a player to use this!'
  error-location: '&cThere is a wrong location of the room to be checked in config!'
  error-checking-player: '&cThe correct use of the command is: /checker check <nickPlayer>'
  already-player-checking: '&cSome player is already being checked!'
  chat-send-to-cheater: '&cJoin the discord! &a LINK'
  cheater-title-up: '&cYou are being checked!'
  cheater-title-down: '&aQuit = BAN'
  send-to-admin: '&aPlayer found! Check it out!'
  player-is-not-online: '&cThis player is not Online!'
  must-check: '&cYou have to check the player! Use the command: /checker check <nick>'
  player-is-not-guilty: '&aYou have been acquitted!'
  admin-player-is-not-guilty: '&aYou acquitted this player!'
  player-admit: '&aYou pleaded guilty!'
  admin-player-admit: '&aYou banned a player. Reason: pleaded guilty!'
  player-detection: '&aDetected you have cheats!'
  admin-player-detection: '&aYou banned a player. Reason: cheats detected!'
  player-quit: '&aYou left while checking out!'
ban-time-hours:
  admit: 15
  detection: 10
  quit: 0
